services:

    nginx:
        build: ./docker/nginx
        container_name: nginx
        restart: always
        command: [ "sh", "-c", "./docker/nginx/init.sh; nginx -g 'daemon off;'" ]
        volumes:
            - ./src:/var/src
            - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
            - ./docker/nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
            - ./docker/nginx/ssl:/etc/ssl/certs
        depends_on:
            - mysql
            - postgres
            - php
        ports:
            - 80:80
            - 443:443

    php:
#        build: ./docker/php-8.2
        build: ./docker/php-7.4
        container_name: php
        command: [ "sh", "-c", "./docker/php/init.sh; php-fpm" ]
        volumes:
            - ./src:/var/src
            - ./docker/etc/php/php.ini:/usr/local/etc/php/php.ini
        ports:
            - 9000:9000
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: "serverName=docker-debug"
            XDEBUG_MODE: "debug"
            XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9099"

    mysql:
        image: mysql:8
        container_name: mysql
        restart: always
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mysql
        volumes:
            - ./docker/mysql:/var/lib/mysql
            - ./docker/etc/mysql:/etc/mysql/conf.d
        ports:
            - 3306:3306

    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        volumes:
            - ./docker/postgres:/var/lib/postgresql

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        depends_on:
            - postgres
            - mysql
        ports:
            - 8080:8080
        environment:
            ADMINER_DEFAULT_SERVER: mysql
